// <auto-generated />
using System;
using CheckScam.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CheckScam.Migrations
{
    [DbContext(typeof(CheckScamDbContext))]
    [Migration("20250622163705_1")]
    partial class _1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CheckScam.Models.ScamImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScamPostId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScamPostId");

                    b.ToTable("ScamImages");
                });

            modelBuilder.Entity("CheckScam.Models.ScamPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SdtScam")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("StkScam")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ScamPosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 3, 23, 10, 4, 47, 0, DateTimeKind.Utc),
                            NoiDung = "Kẻ lừa đảo giả danh nhân viên ngân hàng gọi điện thoại thông báo tài khoản của nạn nhân gặp sự cố và yêu cầu cung cấp thông tin cá nhân, mật khẩu, mã OTP để 'xác minh' hoặc 'khóa tài khoản'.",
                            SdtScam = "84901234567",
                            Status = "approved",
                            StkScam = "Không áp dụng"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 3, 23, 10, 4, 47, 0, DateTimeKind.Utc),
                            NoiDung = "Đối tượng thông báo cho nạn nhân rằng họ đã trúng thưởng một giải thưởng giá trị. Để nhận thưởng, nạn nhân phải chuyển một khoản tiền phí hoặc cung cấp thông tin cá nhân. Sau khi nhận được tiền hoặc thông tin, đối tượng sẽ biến mất.",
                            Status = "approved",
                            StkScam = "Không có thông tin"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 3, 23, 10, 4, 47, 0, DateTimeKind.Utc),
                            NoiDung = "Đối tượng lừa đảo quảng cáo các dự án đầu tư tiền ảo với lợi nhuận cao, cam kết sinh lời nhanh chóng. Sau khi nhận tiền, chúng biến mất hoặc sàn giao dịch sập.",
                            Status = "approved",
                            StkScam = "Nhiều số tài khoản khác nhau"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 3, 23, 10, 19, 47, 0, DateTimeKind.Utc),
                            NoiDung = "Kẻ lừa đảo giả danh nhân viên ngân hàng yêu cầu nạn nhân cung cấp thông tin đăng nhập, mã OTP hoặc chuyển tiền để 'xác minh' tài khoản. Chúng dùng thông tin này để chiếm đoạt tiền.",
                            Status = "approved",
                            StkScam = "Không áp dụng"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 3, 23, 10, 19, 47, 0, DateTimeKind.Utc),
                            NoiDung = "Các đối tượng đăng tin tuyển dụng việc làm online với mức lương hấp dẫn, yêu cầu người lao động đóng phí hoặc đặt cọc trước khi bắt đầu công việc. Sau khi nhận tiền, chúng cắt đứt liên lạc.",
                            Status = "approved"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 3, 23, 10, 21, 8, 0, DateTimeKind.Utc),
                            NoiDung = "Đối tượng lừa đảo sử dụng các trang web hoặc nhóm chat để quảng cáo các dự án đầu tư tài chính với lợi nhuận cao. Sau khi nhận tiền đầu tư, chúng biến mất hoặc ngừng trả lãi.",
                            Status = "approved",
                            StkScam = "Nhiều số tài khoản khác nhau"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 3, 24, 2, 0, 55, 0, DateTimeKind.Utc),
                            NoiDung = "Đối tượng giả danh công an gọi điện thông báo nạn nhân liên quan đến một vụ án nghiêm trọng và yêu cầu chuyển tiền vào tài khoản để xác minh.",
                            SdtScam = "84388388099",
                            Status = "approved"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 3, 24, 2, 1, 14, 0, DateTimeKind.Utc),
                            NoiDung = "Đối tượng quảng cáo các sàn đầu tư tiền ảo, chứng khoán, ngoại hối với lợi nhuận cao bất thường. Sau khi nạn nhân đầu tư, đối tượng biến mất.",
                            Status = "approved",
                            StkScam = "Nhiều số tài khoản khác nhau"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 3, 24, 2, 1, 37, 0, DateTimeKind.Utc),
                            NoiDung = "Đối tượng giả danh nhân viên ngân hàng thông báo tài khoản của nạn nhân có vấn đề, yêu cầu cung cấp thông tin cá nhân, mã OTP để chiếm đoạt tiền.",
                            Status = "approved",
                            StkScam = "Không có thông tin"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 3, 24, 7, 18, 46, 0, DateTimeKind.Utc),
                            NoiDung = "Lừa đảo giả mạo, yêu cầu chuyển tiền vào tài khoản ngân hàng.",
                            SdtScam = "901956846",
                            Status = "approved",
                            StkScam = "1150080072 vcb"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 3, 24, 7, 46, 13, 0, DateTimeKind.Utc),
                            NoiDung = "Đối tượng giả danh nhân viên tổng đài xổ số thông báo trúng giải thưởng lớn và yêu cầu chuyển tiền phí, thuế để nhận thưởng.",
                            SdtScam = "84395642",
                            Status = "approved",
                            StkScam = "Không có thông tin"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 3, 24, 7, 46, 13, 0, DateTimeKind.Utc),
                            NoiDung = "Đối tượng mạo danh công an, viện kiểm sát thông báo nạn nhân liên quan đến vụ án nghiêm trọng và yêu cầu chuyển tiền để xác minh.",
                            SdtScam = "8424848",
                            Status = "approved",
                            StkScam = "Không có thông tin"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 3, 24, 7, 50, 26, 0, DateTimeKind.Utc),
                            NoiDung = "Đối tượng giả mạo nhân viên công ty xổ số thông báo trúng thưởng, yêu cầu nạn nhân chuyển khoản phí nhận thưởng hoặc thuế trước khi nhận giải.",
                            Status = "approved"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 3, 24, 7, 50, 57, 0, DateTimeKind.Utc),
                            NoiDung = "Đối tượng giả danh công an thông báo nạn nhân liên quan đến một vụ án ma túy, rửa tiền và yêu cầu chuyển tiền để xác minh.",
                            SdtScam = "84374602350",
                            Status = "approved"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 3, 24, 7, 50, 57, 0, DateTimeKind.Utc),
                            NoiDung = "Đối tượng lừa đảo qua nhóm 'tuyển cộng tác viên online', yêu cầu chuyển tiền để thực hiện nhiệm vụ và hứa trả hoa hồng, sau đó chiếm đoạt tiền.",
                            SdtScam = "583021",
                            Status = "approved",
                            StkScam = "99006868xxxx"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 3, 24, 7, 50, 57, 0, DateTimeKind.Utc),
                            NoiDung = "Đối tượng hack tài khoản mạng xã hội, nhắn tin cho bạn bè để vay tiền với lý do cấp bách, yêu cầu chuyển tiền vào tài khoản ngân hàng.",
                            Status = "approved",
                            StkScam = "19036281983012 (Techcombank)"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 6, 20, 17, 46, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Thông báo trúng thưởng giả, yêu cầu đóng phí.",
                            SdtScam = "19003439",
                            Status = "approved"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 6, 20, 17, 46, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Lừa đảo qua mua bán hàng online, yêu cầu chuyển tiền đặt cọc.",
                            SdtScam = "0342867523",
                            Status = "approved"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2025, 6, 20, 17, 46, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Số quốc tế giả mạo, yêu cầu cung cấp thông tin cá nhân.",
                            SdtScam = "+8919008198",
                            Status = "approved"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Số từ Guinea, thường liên quan đến lừa đảo tài chính.",
                            SdtScam = "+224",
                            Status = "approved"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Số từ Liberia, thường giả danh tổ chức quốc tế.",
                            SdtScam = "+231",
                            Status = "approved"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Số từ Somalia, liên quan đến lừa đảo qua tin nhắn.",
                            SdtScam = "+252",
                            Status = "approved"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Số từ Moldova, lừa đảo qua cuộc gọi ngắn (Wangiri).",
                            SdtScam = "+373",
                            Status = "approved"
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Số từ Tunisia, giả danh dịch vụ quốc tế.",
                            SdtScam = "+216",
                            Status = "approved"
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Số từ Equatorial Guinea, lừa đảo tài chính.",
                            SdtScam = "+240",
                            Status = "approved"
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Số từ Burkina Faso, lừa đảo qua cuộc gọi.",
                            SdtScam = "+226",
                            Status = "approved"
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Số Hà Nội, giả danh ngân hàng hoặc cơ quan công.",
                            SdtScam = "02439446395",
                            Status = "approved"
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Số TP.HCM, lừa đảo giao hàng giả mạo.",
                            SdtScam = "02822211234",
                            Status = "approved"
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Số dịch vụ giả danh tổng đài hỗ trợ.",
                            SdtScam = "1900123456",
                            Status = "approved"
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Số Hà Nội, mạo danh cơ quan chức năng.",
                            SdtScam = "02499950060",
                            Status = "approved"
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Số TP.HCM, lừa đảo qua tin nhắn.",
                            SdtScam = "02899964439",
                            Status = "approved"
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Số giả danh Đại sứ quán Việt Nam tại Mỹ.",
                            SdtScam = "2028610737",
                            Status = "approved"
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Số từ Campuchia, liên quan đến lừa đảo trực tuyến.",
                            SdtScam = "+855714749087",
                            Status = "approved"
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Số có đầu không an toàn từ Ascension.",
                            SdtScam = "+2471234567",
                            Status = "approved"
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Số có đầu không an toàn từ Valparaiso.",
                            SdtScam = "+5631234567",
                            Status = "approved"
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Số có đầu không an toàn từ mạng quốc tế.",
                            SdtScam = "+88212345678",
                            Status = "approved"
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Số TP.HCM giả danh Digitel.",
                            SdtScam = "02888123456",
                            Status = "approved"
                        });
                });

            modelBuilder.Entity("CheckScam.Models.ScamUrl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("ScamUrls");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Giả mạo Amazon, có thể dụ nhập thông tin hoặc bán hàng giả.",
                            Status = "pending",
                            Url = "amazou2.com"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Giả mạo TikTok, dụ người dùng nhập thông tin hoặc tải ứng dụng giả.",
                            Status = "pending",
                            Url = "vnttiktok.cc"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Liên quan đến giao dịch game, yêu cầu thanh toán trước.",
                            Status = "pending",
                            Url = "napgamex5.com"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Bán thẻ game/tài khoản, thường không giao hàng sau thanh toán.",
                            Status = "pending",
                            Url = "muacard.online"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Giả mạo trung tâm thương mại, quảng cáo giảm giá nhưng không giao.",
                            Status = "pending",
                            Url = "mall2024tn.com"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Giả danh đối tác chiến lược của công ty lớn, có thể lừa đảo đầu tư.",
                            Status = "pending",
                            Url = "doitacchienluoc.com"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Giả mạo eBay, bán hàng giá rẻ, có thể không giao hoặc giao hàng giả.",
                            Status = "pending",
                            Url = "ebayglobal.store"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Tên miền không rõ ràng, có thể liên quan đến lừa đảo tài chính.",
                            Status = "pending",
                            Url = "hhkkd3.com"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Giả danh công ty phát triển TP.HCM, có thể dụ đầu tư hoặc bán hàng giả.",
                            Status = "pending",
                            Url = "hcmphattrien.com"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Giả mạo tuyển dụng Apple, có thể thu thập thông tin cá nhân.",
                            Status = "pending",
                            Url = "tuyendungapple.com"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Tên miền không rõ ràng, có thể liên quan đến lừa đảo tài chính/game.",
                            Status = "pending",
                            Url = "sp6708p.com"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Giả mạo Giao Hàng Tiết Kiệm, gửi link thanh toán giả qua SMS/email.",
                            Status = "pending",
                            Url = "ctygiaohangtietkiemm1.com"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Giả mạo TikTok Shop, dụ nhập thông tin hoặc thanh toán.",
                            Status = "pending",
                            Url = "tiktokvn1.shop"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Tên miền không rõ ràng, có thể giả danh công ty đầu tư.",
                            Status = "pending",
                            Url = "ssiamvna.asia"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Tương tự ssiamvna.asia, có thể liên quan đến lừa đảo đầu tư.",
                            Status = "pending",
                            Url = "ssiamvnx.asia"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Giả mạo Vingroup, bán sản phẩm/dịch vụ giả hoặc thu thập thông tin.",
                            Status = "pending",
                            Url = "vingroup.store"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Giả mạo Vingroup, liên quan đến lừa đảo đầu tư.",
                            Status = "pending",
                            Url = "vingroupventures.vip"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Giả mạo Vingroup, có thể dụ đầu tư hoặc bán hàng giả.",
                            Status = "pending",
                            Url = "vingroupglobal.com"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Giả mạo Vingroup, liên quan đến lừa đảo đầu tư.",
                            Status = "pending",
                            Url = "vingroupventures.top"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Giả mạo Vingroup, có thể dụ đầu tư hoặc thu thập thông tin.",
                            Status = "pending",
                            Url = "vingroupventures.site"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Tên miền không rõ ràng, có thể liên quan đến lừa đảo tài chính.",
                            Status = "pending",
                            Url = "sforecast.com"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Tương tự ssiamvna.asia, có thể giả danh công ty đầu tư.",
                            Status = "pending",
                            Url = "ssiamvnm.asia"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Tên miền không rõ ràng, có thể liên quan đến lừa đảo tài chính/game.",
                            Status = "pending",
                            Url = "pt31.com"
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Tên miền không rõ ràng, có thể liên quan đến lừa đảo quảng cáo.",
                            Status = "pending",
                            Url = "aguih.com"
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Giả danh tổ chức ASEAN, có thể dụ đầu tư hoặc thu thập thông tin.",
                            Status = "pending",
                            Url = "asean-sc.com"
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Giả mạo cửa hàng trực tuyến, có thể không giao hàng hoặc bán hàng giả.",
                            Status = "pending",
                            Url = "lynstore.net"
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Giả danh sàn giao dịch chứng khoán, có thể lừa đảo đầu tư.",
                            Status = "pending",
                            Url = "stratestokex.vn"
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Tên miền không rõ ràng, có thể liên quan đến lừa đảo tài chính.",
                            Status = "pending",
                            Url = "lotusfn.com"
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Liên kết phụ, có thể dẫn đến trang lừa đảo trên tên miền inkbio.me.",
                            Status = "pending",
                            Url = "inkbio.me/hoanglongfn"
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Giả mạo MetLife, có thể dụ mua bảo hiểm hoặc thu thập thông tin.",
                            Status = "pending",
                            Url = "metlife222.com"
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Giả mạo ứng dụng hoặc cửa hàng, có thể dụ tải phần mềm độc hại.",
                            Status = "pending",
                            Url = "donkihote.xyz/app"
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Liên quan đến nạp game, yêu cầu thanh toán trước nhưng không giao.",
                            Status = "pending",
                            Url = "playkuvip.club"
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Liên kết phụ, có thể dẫn đến trang lừa đảo trên tên miền inkbio.me.",
                            Status = "pending",
                            Url = "inkbio.me/hoanglong.com"
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Giả mạo xổ số Việt Nam, dụ nhập thông tin hoặc thanh toán.",
                            Status = "pending",
                            Url = "lotteryvietnamese.com/h5"
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Liên quan đến nạp game, yêu cầu thanh toán trước nhưng không giao.",
                            Status = "pending",
                            Url = "bumvip68.club"
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Tên miền không rõ ràng, có thể giả danh công ty đầu tư.",
                            Status = "pending",
                            Url = "ssiamvn.com"
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Giả mạo dịch vụ hoặc ứng dụng, có thể dụ nhập thông tin.",
                            Status = "pending",
                            Url = "tikiz.vip"
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Giả mạo sàn Nasdaq, dụ đầu tư giả.",
                            Status = "pending",
                            Url = "nasdaqvnn.com"
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Hứa lợi nhuận cao qua đầu tư PAMM, có thể là lừa đảo tài chính.",
                            Status = "pending",
                            Url = "pamm.fvptrade.com"
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Giả danh quỹ đầu tư, dụ đầu tư giả.",
                            Status = "pending",
                            Url = "fund.almohannadigroup.com"
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Giả mạo ví MoMo, đánh cắp thông tin tài khoản qua link giả.",
                            Status = "pending",
                            Url = "chanlemomo.win"
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Giả mạo ví MoMo, dụ nhập thông tin tài khoản.",
                            Status = "pending",
                            Url = "chanlemomo.cc"
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Quảng cáo trên TikTok, dụ đăng ký nhận phần thưởng, thu thập thông tin.",
                            Status = "pending",
                            Url = "rewardsgiantusa.com"
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Bán thực phẩm bổ sung Emma, Trustpilot chấm 2.0/5, 76% đánh giá tiêu cực.",
                            Status = "pending",
                            Url = "emmarelief.com"
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Bán sản phẩm da giá rẻ, giao hàng giả hoặc không giao.",
                            Status = "pending",
                            Url = "trendcraftleather.com"
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Giả mạo Tiffany & Co., bán trang sức giá thấp, không liên kết chính thức.",
                            Status = "pending",
                            Url = "tiffanycoshop.com"
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Bán tài khoản/vật phẩm Lords Mobile, lừa tiền qua PayPal, không giao.",
                            Status = "pending",
                            Url = "lords-mob.com"
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Giả mạo PayPal, dụ nhập thông tin đăng nhập qua email giả mạo.",
                            Status = "pending",
                            Url = "paypa1.com"
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Giả mạo PayPal, đánh cắp thông tin đăng nhập qua email lừa đảo.",
                            Status = "pending",
                            Url = "paypaysecurity.com"
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Giả mạo bán giày Hoka, tên miền mới, thiết kế cẩu thả.",
                            Status = "pending",
                            Url = "onlinehokasale.com"
                        },
                        new
                        {
                            Id = 51,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Giả mạo DMV Oklahoma, gửi link thanh toán phạt giao thông giả qua SMS.",
                            Status = "pending",
                            Url = "ok.gov-yiw.vip"
                        },
                        new
                        {
                            Id = 52,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Giả mạo App Store Việt Nam, lừa người dùng cài ứng dụng giả mạo.",
                            Status = "pending",
                            Url = "appstorevn.cc"
                        },
                        new
                        {
                            Id = 53,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Giả danh công ty bảo hiểm, dụ người dùng đầu tư giả.",
                            Status = "pending",
                            Url = "baohiemxlife.com"
                        },
                        new
                        {
                            Id = 54,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Giả mạo Grab Việt Nam, lừa nhập thông tin thanh toán.",
                            Status = "pending",
                            Url = "grab-vn.app"
                        },
                        new
                        {
                            Id = 55,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Giả mạo Meta (Facebook), quảng cáo tuyển dụng giả mạo.",
                            Status = "pending",
                            Url = "meta-vn.store"
                        },
                        new
                        {
                            Id = 56,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Trang bán thẻ cào siêu rẻ, yêu cầu chuyển khoản trước rồi không giao.",
                            Status = "pending",
                            Url = "thecaosieure.net"
                        },
                        new
                        {
                            Id = 57,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Giả mạo liên kết MoMo - VNPAY, dụ người dùng nhập OTP.",
                            Status = "pending",
                            Url = "momo-vnpay.com"
                        },
                        new
                        {
                            Id = 58,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Giả mạo trang xổ số, thu thập dữ liệu cá nhân.",
                            Status = "pending",
                            Url = "xoso68vn.me"
                        },
                        new
                        {
                            Id = 59,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Giả danh dịch vụ cho vay online, lừa cung cấp thông tin cá nhân.",
                            Status = "pending",
                            Url = "vaytienonline365.store"
                        },
                        new
                        {
                            Id = 60,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Giả mạo EVN (Điện lực), gửi hoá đơn giả qua email/SMS.",
                            Status = "pending",
                            Url = "evnthanhtoan.cc"
                        },
                        new
                        {
                            Id = 61,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Giả danh Viettel, yêu cầu xác minh tài khoản qua link giả.",
                            Status = "pending",
                            Url = "viettelxacminh.com"
                        },
                        new
                        {
                            Id = 62,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Giả mạo Shopee tuyển dụng, thu thập hồ sơ cá nhân.",
                            Status = "pending",
                            Url = "tuyendung-shopee.net"
                        },
                        new
                        {
                            Id = 63,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Giả mạo trang thương mại Shopee, yêu cầu thanh toán qua ví giả.",
                            Status = "pending",
                            Url = "vnshopeex.com"
                        },
                        new
                        {
                            Id = 64,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Giả mạo MyViettel, yêu cầu xác thực qua OTP.",
                            Status = "pending",
                            Url = "myviettelverify.cc"
                        },
                        new
                        {
                            Id = 65,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Giả mạo EVN Hà Nội, gửi link thanh toán điện giả mạo.",
                            Status = "pending",
                            Url = "evnhanoi-pay.net"
                        },
                        new
                        {
                            Id = 66,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Trang bán thẻ Viettel giả, yêu cầu chuyển khoản không hoàn lại.",
                            Status = "pending",
                            Url = "gachtheviettel.net"
                        },
                        new
                        {
                            Id = 67,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Giả mạo thanh toán Mobifone, đánh cắp thông tin thanh toán.",
                            Status = "pending",
                            Url = "mobifonepay.site"
                        },
                        new
                        {
                            Id = 68,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Giả mạo Facebook Việt Nam, yêu cầu xác minh tài khoản.",
                            Status = "pending",
                            Url = "vn-facebook.app"
                        },
                        new
                        {
                            Id = 69,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Giả danh sự kiện ZaloPay, lừa người dùng nhập OTP.",
                            Status = "pending",
                            Url = "zalopay-event.com"
                        },
                        new
                        {
                            Id = 70,
                            CreatedAt = new DateTime(2025, 6, 22, 22, 12, 0, 0, DateTimeKind.Utc),
                            NoiDung = "Giả mạo chương trình lì xì, yêu cầu nhập tài khoản ngân hàng.",
                            Status = "pending",
                            Url = "lixi2025-event.net"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CheckScam.Models.ScamImage", b =>
                {
                    b.HasOne("CheckScam.Models.ScamPost", "ScamPost")
                        .WithMany("Images")
                        .HasForeignKey("ScamPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScamPost");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CheckScam.Models.ScamPost", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
